apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mcp-test-environments
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        namespace: mcp-test-dev
        replicaCount: "1"
        cpuRequest: "100m"
        memoryRequest: "128Mi"
        cpuLimit: "200m"
        memoryLimit: "256Mi"
      - env: prod
        namespace: mcp-test-prod
        replicaCount: "3"
        cpuRequest: "200m"
        memoryRequest: "256Mi"
        cpuLimit: "500m"
        memoryLimit: "512Mi"
  template:
    metadata:
      name: 'mcp-test-{{env}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/geek0ps/mcp-test-chart
        targetRevision: main
        helm:
          parameters:
          - name: environment
            value: '{{env}}'
          - name: replicaCount
            value: '{{replicaCount}}'
          - name: resources.requests.cpu
            value: '{{cpuRequest}}'
          - name: resources.requests.memory
            value: '{{memoryRequest}}'
          - name: resources.limits.cpu
            value: '{{cpuLimit}}'
          - name: resources.limits.memory
            value: '{{memoryLimit}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m