environment: prod
replicaCount: 3

image:
  tag: "stable"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: mcp-test-prod.example.com
      paths:
        - path: /
          pathType: Prefix